# Site settings
author: Natalie Halawani
title: Online Web Developer
header-img: img/home-bg.png
email: hala1224@gmail.com
copyright_name: Natalie Halawani
description: > # this means to ignore newlines until "baseurl:"
  JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hala1224

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
